#!/usr/bin/env python3
"""
Medical Spine Segmentation Scenario
Orchestrator for running base (pure ML) vs venturalitica (governance-instrumented) versions.

Usage:
    python main.py --scenario base               # MONAI inference, no governance
    python main.py --scenario totalseg           # TotalSegmentator v2 inference, no governance
    python main.py --scenario venturalitica      # MONAI inference + compliance audit
    python main.py --scenario compliance         # Audit existing cohort_results.csv (MONAI)
    python main.py --scenario compliance-totalseg # Audit existing cohort_results_totalseg.csv
    python main.py --scenario full-pipeline      # MONAI inference + compliance audit
    python main.py --scenario compare            # Audit BOTH cohorts and emit side-by-side report
"""

import sys
import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="Medical Spine Segmentation - MONAI vs TotalSegmentator with Venturalitica governance"
    )
    parser.add_argument(
        "--scenario",
        choices=[
            "base",
            "totalseg",
            "venturalitica",
            "compliance",
            "compliance-totalseg",
            "full-pipeline",
            "compare",
        ],
        default="base",
        help="Which scenario to run",
    )
    parser.add_argument(
        "--model-path",
        help="Path to MONAI model bundle",
    )
    parser.add_argument(
        "--data-path",
        help="Path to DICOM data directory",
    )

    args = parser.parse_args()

    # Add the scenario modules to sys.path
    scenario_dir = Path(__file__).parent
    base_path = scenario_dir / "base_medical"
    vl_path = scenario_dir / "venturalitica_medical"
    shared_path = scenario_dir / "shared_data"

    # Default model path (only used by the MONAI scenarios)
    model_path = args.model_path or str(
        shared_path / "models" / "wholeBody_ct_segmentation"
    )
    data_path = args.data_path

    if args.scenario == "base":
        sys.path.insert(0, str(base_path))
        from model_evaluation import main as base_main

        print("=" * 60)
        print("  Running Base Evaluation (MONAI wholeBody_ct_segmentation)")
        print("=" * 60)
        base_main(model_path=model_path, data_path=data_path)

    elif args.scenario == "totalseg":
        sys.path.insert(0, str(base_path))
        from totalseg_evaluation import main as ts_main

        print("=" * 60)
        print("  Running TotalSegmentator v2 Evaluation")
        print("=" * 60)
        ts_main(data_path=data_path)

    elif args.scenario == "venturalitica":
        sys.path.insert(0, str(vl_path))
        sys.path.insert(0, str(base_path))
        import venturalitica
        from model_evaluation import main as base_main

        print("=" * 60)
        print("  Running Venturalitica Pipeline (MONAI + Governance)")
        print("=" * 60)
        with venturalitica.monitor(
            name="Spine-Mets GPU Inference",
            label="Medical Device AI - EU AI Act Art. 6(1)",
        ):
            base_main(model_path=model_path, data_path=data_path)

        # Run compliance audit after inference
        from compliance_suite import run_compliance_suite
        run_compliance_suite(model_label="MONAI wholeBody_ct_segmentation")

    elif args.scenario in ("compliance", "compliance-totalseg"):
        # Compliance requires inference results (generated by running base/totalseg first)
        cohort_file = (
            "cohort_results_totalseg.csv"
            if args.scenario == "compliance-totalseg"
            else "cohort_results.csv"
        )
        model_label = (
            "TotalSegmentator v2 (vertebrae)"
            if args.scenario == "compliance-totalseg"
            else "MONAI wholeBody_ct_segmentation"
        )
        results_path = shared_path / cohort_file
        if not results_path.exists():
            print(f"ERROR: No inference results found at {results_path}")
            inference_scenario = "totalseg" if args.scenario == "compliance-totalseg" else "venturalitica"
            print(f"  Run inference first: python main.py --scenario {inference_scenario} --data-path shared_data/dicom")
            sys.exit(1)

        sys.path.insert(0, str(vl_path))
        from compliance_suite import run_compliance_suite

        run_compliance_suite(cohort_file=cohort_file, model_label=model_label)

    elif args.scenario == "full-pipeline":
        sys.path.insert(0, str(vl_path))
        sys.path.insert(0, str(base_path))
        import venturalitica
        from model_evaluation import main as base_main

        print("=" * 60)
        print("  Running Full Pipeline: MONAI inference + compliance audit")
        print("=" * 60)

        with venturalitica.monitor(
            name="Spine-Mets Full Pipeline",
            label="Medical Device AI - EU AI Act Art. 6(1)",
        ):
            base_main(model_path=model_path, data_path=data_path)

            print("\n" + "=" * 60)
            from compliance_suite import run_compliance_suite
            run_compliance_suite(model_label="MONAI wholeBody_ct_segmentation")

    elif args.scenario == "compare":
        # Audit BOTH cohorts (MONAI and TotalSegmentator) and emit a
        # side-by-side comparison so the demo can show both models
        # going through the same VL governance gate.
        monai_path = shared_path / "cohort_results.csv"
        ts_path = shared_path / "cohort_results_totalseg.csv"
        if not monai_path.exists() or not ts_path.exists():
            print("ERROR: comparison requires both inference runs to be present:")
            print(f"  {monai_path} {'(present)' if monai_path.exists() else '(MISSING)'}")
            print(f"  {ts_path} {'(present)' if ts_path.exists() else '(MISSING)'}")
            print("  Run inference first:")
            if not monai_path.exists():
                print("    python main.py --scenario venturalitica --data-path shared_data/dicom")
            if not ts_path.exists():
                print("    python main.py --scenario totalseg --data-path shared_data/dicom")
            sys.exit(1)

        sys.path.insert(0, str(vl_path))
        from compliance_suite import run_compliance_suite
        from compare_models import emit_comparison_report

        print("=" * 60)
        print("  Cross-model compliance comparison")
        print("=" * 60)

        monai_out = run_compliance_suite(
            cohort_file="cohort_results.csv",
            model_label="MONAI wholeBody_ct_segmentation",
        )
        print("\n")
        ts_out = run_compliance_suite(
            cohort_file="cohort_results_totalseg.csv",
            model_label="TotalSegmentator v2 (vertebrae)",
        )

        emit_comparison_report(
            monai=monai_out,
            totalseg=ts_out,
            output_path=scenario_dir / "compare_report.md",
        )


if __name__ == "__main__":
    main()
